name: Node CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (CI safe)
        run: npm ci

      - name: Run tests
        run: npm test
